//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blanquita_Inventarios.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codigos
    {
        public int IdCodigo { get; set; }
        public int IdConfiguracion { get; set; }
        public string Codigo { get; set; }
        public System.DateTime FechaGeneracion { get; set; }
        public int IdUsuarioGenero { get; set; }
        public Nullable<int> IdUsuarioUtilizo { get; set; }
        public Nullable<int> IdAccion { get; set; }
        public Nullable<System.DateTime> FechaUtilizo { get; set; }
        public int IdEstatus { get; set; }
    
        public virtual AccionesCodigo AccionesCodigo { get; set; }
        public virtual EstatusCodigo EstatusCodigo { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Configuraciones Configuraciones { get; set; }
    }
}
