//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blanquita_Inventarios.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuraciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Configuraciones()
        {
            this.Codigos = new HashSet<Codigos>();
            this.Zonas = new HashSet<Zonas>();
        }
    
        public int IdConfiguracion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string NombreInventario { get; set; }
        public string ServidorIP { get; set; }
        public string Instancia { get; set; }
        public string Puerto { get; set; }
        public string Usuario { get; set; }
        public string Password { get; set; }
        public string BaseDatos { get; set; }
        public string Almacen { get; set; }
        public bool Activo { get; set; }
        public bool Cerrado { get; set; }
        public Nullable<System.DateTime> FechaCerrado { get; set; }
        public bool Deshabilitado { get; set; }
        public Nullable<System.DateTime> FechaDeshabilitado { get; set; }
        public Nullable<System.DateTime> FechaUltimoRespaldo { get; set; }
        public Nullable<System.DateTime> FechaEliminado { get; set; }
        public bool Procesado { get; set; }
        public bool AjustesAplicados { get; set; }
        public Nullable<System.DateTime> FechaAjustes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Codigos> Codigos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zonas> Zonas { get; set; }
    }
}
