//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blanquita_Inventarios.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marbetes
    {
        public int IdMarbete { get; set; }
        public int IdZona { get; set; }
        public int Marbete { get; set; }
        public string Capturo { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public int Estatus { get; set; }
    
        public virtual Zonas Zonas { get; set; }
    }
}
