//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blanquita_Inventarios.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zonas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zonas()
        {
            this.Marbetes = new HashSet<Marbetes>();
        }
    
        public int IdZona { get; set; }
        public int IdConfiguracion { get; set; }
        public string Zona { get; set; }
        public int MarbeteInicial { get; set; }
        public int MarbeteFinal { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaEliminado { get; set; }
        public bool MarbetesCreados { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marbetes> Marbetes { get; set; }
        public virtual Configuraciones Configuraciones { get; set; }
    }
}
