//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blanquita_Inventarios.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Blanquita_Inventarios.Entities;
    
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InventariosEntities : DbContext
    {
        public InventariosEntities()
            : base("name=InventariosEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Perfiles> Perfiles { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<AccionesCodigo> AccionesCodigo { get; set; }
        public virtual DbSet<Codigos> Codigos { get; set; }
        public virtual DbSet<EstatusCodigo> EstatusCodigo { get; set; }
        public virtual DbSet<Marbetes> Marbetes { get; set; }
        public virtual DbSet<Zonas> Zonas { get; set; }
        public virtual DbSet<Configuraciones> Configuraciones { get; set; }
    
        public virtual ObjectResult<Search_ItmsGrpName_Result> Search_ItmsGrpName(string itemCode)
        {
            var itemCodeParameter = itemCode != null ?
                new ObjectParameter("ItemCode", itemCode) :
                new ObjectParameter("ItemCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_ItmsGrpName_Result>("Search_ItmsGrpName", itemCodeParameter);
        }
    
        public virtual ObjectResult<Report_SAPBarcodes_Result> Report_SAPBarcodes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_SAPBarcodes_Result>("Report_SAPBarcodes");
        }
    
        public virtual ObjectResult<Report_ItemsByAlmacen_Result> Report_ItemsByAlmacen(string whsCode)
        {
            var whsCodeParameter = whsCode != null ?
                new ObjectParameter("WhsCode", whsCode) :
                new ObjectParameter("WhsCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_ItemsByAlmacen_Result>("Report_ItemsByAlmacen", whsCodeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Get_TotalMarbetesByConfiguracion(Nullable<int> idConfiguracion)
        {
            var idConfiguracionParameter = idConfiguracion.HasValue ?
                new ObjectParameter("IdConfiguracion", idConfiguracion) :
                new ObjectParameter("IdConfiguracion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Get_TotalMarbetesByConfiguracion", idConfiguracionParameter);
        }
    
        public virtual ObjectResult<Report_ListadoCategorias_Result> Report_ListadoCategorias(string textoInicio)
        {
            var textoInicioParameter = textoInicio != null ?
                new ObjectParameter("TextoInicio", textoInicio) :
                new ObjectParameter("TextoInicio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_ListadoCategorias_Result>("Report_ListadoCategorias", textoInicioParameter);
        }
    
        public virtual ObjectResult<Report_CostoCeroByInventario_Result> Report_CostoCeroByInventario(string whsCode, string xmlStr)
        {
            var whsCodeParameter = whsCode != null ?
                new ObjectParameter("WhsCode", whsCode) :
                new ObjectParameter("WhsCode", typeof(string));
    
            var xmlStrParameter = xmlStr != null ?
                new ObjectParameter("XmlStr", xmlStr) :
                new ObjectParameter("XmlStr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_CostoCeroByInventario_Result>("Report_CostoCeroByInventario", whsCodeParameter, xmlStrParameter);
        }
    
        public virtual ObjectResult<Search_ItemExistenciaSAP_Result> Search_ItemExistenciaSAP(string itemCode, string whsCode)
        {
            var itemCodeParameter = itemCode != null ?
                new ObjectParameter("ItemCode", itemCode) :
                new ObjectParameter("ItemCode", typeof(string));
    
            var whsCodeParameter = whsCode != null ?
                new ObjectParameter("WhsCode", whsCode) :
                new ObjectParameter("WhsCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_ItemExistenciaSAP_Result>("Search_ItemExistenciaSAP", itemCodeParameter, whsCodeParameter);
        }
    
        public virtual ObjectResult<Report_InformacionSAPxPorProcesar_Result> Report_InformacionSAPxPorProcesar(string whsCode, string xmlStr)
        {
            var whsCodeParameter = whsCode != null ?
                new ObjectParameter("WhsCode", whsCode) :
                new ObjectParameter("WhsCode", typeof(string));
    
            var xmlStrParameter = xmlStr != null ?
                new ObjectParameter("XmlStr", xmlStr) :
                new ObjectParameter("XmlStr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_InformacionSAPxPorProcesar_Result>("Report_InformacionSAPxPorProcesar", whsCodeParameter, xmlStrParameter);
        }
    
        public virtual ObjectResult<Report_InventarioProcesar_Result> Report_InventarioProcesar(string whsCode, string xmlStr)
        {
            var whsCodeParameter = whsCode != null ?
                new ObjectParameter("WhsCode", whsCode) :
                new ObjectParameter("WhsCode", typeof(string));
    
            var xmlStrParameter = xmlStr != null ?
                new ObjectParameter("XmlStr", xmlStr) :
                new ObjectParameter("XmlStr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_InventarioProcesar_Result>("Report_InventarioProcesar", whsCodeParameter, xmlStrParameter);
        }
    }
}
